name: HeavyIndustry
version: 1.22-R3-ALPHA-HI
main: me.capit.HeavyIndustry.HeavyIndustry

website: https://github.com/Wehttam664/Organizations/wiki
description: GameData_HeavyIndustry
author: Wehttam664
preix: HeavyIndustry
    
permissions:
  industry.*:
    description: 'Global HeavyIndustry permission.'
  industry.reload:
    description: 'Reloads HeavyIndustry configuration.'
    
commands:
  industry:
    description: 'Core HeavyIndustry command.'
    usage: /industry [args]
